/**
 * OrangeHRM Suite - Selectors
 * Centralized UI selectors for OrangeHRM pages
 */

export const selectors = {
  login: {
    usernameInput: '#orangehrm-username',
    passwordInput: '#orangehrm-password',
    submitButton: 'button[type="submit"]',
    errorMessage: '.oxd-alert-content',
    logoutButton: 'button:has-text("Logout")',
    rememberMeCheckbox: 'input[type="checkbox"]',
    rememberMeLabel: 'label:has-text("Remember Me")',
  },

  dashboard: {
    heading: 'h1:has-text("Dashboard")',
    userDropdown: '.oxd-userdropdown-tab',
    logoutOption: 'a:has-text("Logout")',
    quickLaunchWidget: '.orangehrm-quick-launch',
    quickLaunchLinks: '.orangehrm-quick-launch .oxd-grid-item',
    assignLeaveLink: 'p:has-text("Assign Leave")',
    leaveListLink: 'p:has-text("Leave List")',
    timesheetsLink: 'p:has-text("Timesheets")',
    applyLeaveLink: 'p:has-text("Apply Leave")',
    myLeaveLink: 'p:has-text("My Leave")',
    myTimesheetLink: 'p:has-text("My Timesheet")',
    widgetContainer: '.oxd-grid-item--gutters',
    employeesOnLeaveWidget: '.orangehrm-employees-on-leave',
    timeAtWorkWidget: '.orangehrm-time-at-work',
    myActionsWidget: '.orangehrm-my-actions',
    buzzLatestPostsWidget: '.orangehrm-buzz-latest-posts',
    dashboardWidgets: '.oxd-layout-container',
  },

  pim: {
    sidebarLink: 'a:has-text("PIM")',
    employeeListLink: 'a:has-text("Employee List")',
    addEmployeeButton: 'button:has-text("Add")',
    firstNameInput: 'input[placeholder="First Name"]',
    lastNameInput: 'input[placeholder="Last Name"]',
    employeeIdInput: 'input[placeholder="Employee Id"]',
    emailInput: 'input[type="email"]',
    photoInput: 'input[type="file"]',
    saveButton: 'button[type="submit"]:has-text("Save")',
    employeeTable: '.oxd-table-body',
    employeeRow: (employeeId: string) => `tr:has-text("${employeeId}")`,
    firstNameField: 'input[placeholder="First Name"]',
    searchButton: 'button:has-text("Search")',
    fieldError: (fieldName: string) => `div:has-text("${fieldName}") ~ div.oxd-form-row-error`,
    requiredError: '.oxd-input-group__error-message',
    paginationNext: 'button[aria-label="Next"]',
    paginationPrev: 'button[aria-label="Previous"]',
    paginationInfo: '.oxd-table-footer',
    totalRecordsLabel: '.orangehrm-bottom-container span',
    contactDetailsTab: 'a:has-text("Contact Details")',
    streetAddressInput: 'input[placeholder="Street 1"]',
    cityInput: 'input[placeholder="City"]',
    phoneInput: 'input[placeholder="Home"]',
    mobileInput: 'input[placeholder="Mobile"]',
    workEmailInput: 'input[placeholder="Work Email"]',
    auditTrail: '.orangehrm-audit-trail',
    createdByField: '.createdBy',
    createdAtField: '.createdAt',
  },

  leave: {
    sidebarLink: 'a:has-text("Leave")',
    applyLeaveLink: 'a:has-text("Apply Leave")',
    leaveListLink: 'a:has-text("My Leave")',
    leaveTypeSelect: '.oxd-select-text',
    leaveTypeOption: (leaveType: string) => `.oxd-select-dropdown span:has-text("${leaveType}")`,
    fromDateInput: 'input[placeholder="yyyy-mm-dd"]',
    toDateInput: 'input[placeholder="yyyy-mm-dd"]',
    commentTextarea: 'textarea',
    submitButton: 'button[type="submit"]:has-text("Apply")',
    leaveTable: '.oxd-table-body',
    leaveRow: (leaveId: string) => `tr:has-text("${leaveId}")`,
    leaveStatus: (leaveId: string) => `tr:has-text("${leaveId}") .oxd-table-cell:last-child`,
    approveButton: 'button:has-text("Approve")',
    rejectButton: 'button:has-text("Reject")',
    rejectReasonTextarea: '.orangehrm-modal-footer textarea',
    confirmRejectButton: '.orangehrm-modal-footer button:has-text("Reject")',
    cancelLeaveButton: 'button:has-text("Cancel Leave")',
    overlapError: '.oxd-alert--error:has-text("overlap")',
    leaveBalanceTable: '.orangehrm-leave-balance',
    leaveBalanceRow: (leaveType: string) => `.orangehrm-leave-balance tr:has-text("${leaveType}")`,
    filterFromDate: 'input[placeholder="yyyy-mm-dd"]:first-of-type',
    filterToDate: 'input[placeholder="yyyy-mm-dd"]:last-of-type',
    filterStatusSelect: '.oxd-select-text',
    filterButton: 'button:has-text("Search")',
  },

  admin: {
    sidebarLink: 'a:has-text("Admin")',
    usersLink: 'a:has-text("Users")',
    jobTitlesLink: 'a:has-text("Job Titles")',
    addUserButton: 'button:has-text("Add")',
    usernameInput: 'input[placeholder="Username"]',
    passwordInput: 'input[type="password"]',
    userTable: '.oxd-table-body',
    addJobTitleButton: 'button:has-text("Add")',
    jobTitleInput: 'input[placeholder="Job Title"]',
  },

  reporting: {
    sidebarLink: 'a:has-text("Reports")',
    reportsHeading: 'h1:has-text("Reports")',
    generateButton: 'button:has-text("Generate")',
    reportTypeSelect: '.oxd-select-text',
    reportTypeOption: (reportType: string) => `.oxd-select-dropdown span:has-text("${reportType}")`,
    reportTable: '.oxd-table-body',
    reportRow: (reportName: string) => `.oxd-table-body tr:has-text("${reportName}")`,
    reportNameInput: 'input[placeholder="Type for hints..."]',
    displayFieldsSection: '.orangehrm-display-fields',
    includeHeaderCheckbox: 'input[type="checkbox"]',
    runReportButton: 'button:has-text("Run Report")',
    reportResultTable: '.orangehrm-report-table',
    reportResultRow: '.orangehrm-report-table .oxd-table-row',
    noRecordsMessage: '.oxd-table-card p:has-text("No Records Found")',
    exportButton: 'button:has-text("Export")',
    exportPdfOption: 'a:has-text("Export as PDF")',
    exportExcelOption: 'a:has-text("Export as Excel")',
    exportCsvOption: 'a:has-text("Export as CSV")',
    filterPanel: '.orangehrm-report-filter-panel',
    employeeNameFilter: 'input[placeholder="Type for hints..."]',
    departmentFilter: '.oxd-select-text:has-text("Department")',
    fromDateFilter: 'input[placeholder="yyyy-mm-dd"]:first-of-type',
    toDateFilter: 'input[placeholder="yyyy-mm-dd"]:last-of-type',
    statusFilter: '.oxd-select-text:has-text("Status")',
    applyFiltersButton: 'button:has-text("Search")',
    resetFiltersButton: 'button:has-text("Reset")',
    saveFilterButton: 'button:has-text("Save")',
    filterNameInput: 'input[placeholder="Filter Name"]',
    savedFiltersDropdown: '.oxd-select-text:has-text("Saved Filters")',
    scheduleTab: 'a:has-text("Schedule")',
    scheduleFrequencySelect: '.oxd-select-text:has-text("Frequency")',
    scheduleFrequencyOption: (freq: string) => `.oxd-select-dropdown span:has-text("${freq}")`,
    scheduleDaySelect: '.oxd-select-text:has-text("Day")',
    scheduleTimeInput: 'input[placeholder="HH:MM"]',
    recipientsInput: 'input[placeholder="Recipients"]',
    saveScheduleButton: 'button:has-text("Save Schedule")',
    cancelScheduleButton: 'button:has-text("Cancel Schedule")',
    scheduledReportsList: '.orangehrm-scheduled-reports',
    scheduledReportRow: (reportName: string) =>
      `.orangehrm-scheduled-reports tr:has-text("${reportName}")`,
    executionHistoryTab: 'a:has-text("Execution History")',
    executionHistoryTable: '.orangehrm-execution-history',
    executionHistoryRow: '.orangehrm-execution-history .oxd-table-row',
    analyticsTab: 'a:has-text("Analytics")',
    dashboardMetrics: '.orangehrm-analytics-metrics',
    trendAnalysisChart: '.orangehrm-trend-analysis',
    comparisonChart: '.orangehrm-comparison-chart',
    chartContainer: '.orangehrm-chart-container',
    analyticsExportButton: 'button:has-text("Export Analytics")',
    customViewButton: 'button:has-text("Create Custom View")',
    customViewNameInput: 'input[placeholder="View Name"]',
    timePeriodSelect: '.oxd-select-text:has-text("Time Period")',
    permissionsTab: 'a:has-text("Permissions")',
    shareButton: 'button:has-text("Share")',
    shareWithInput: 'input[placeholder="Search users or departments"]',
    visibilitySelect: '.oxd-select-text:has-text("Visibility")',
    visibilityOption: (level: string) => `.oxd-select-dropdown span:has-text("${level}")`,
    accessHistoryTab: 'a:has-text("Access History")',
    accessHistoryTable: '.orangehrm-access-history',
    unauthorizedMessage: '.orangehrm-unauthorized:has-text("You do not have permission")',
    reportAccessRow: (username: string) =>
      `.orangehrm-access-history tr:has-text("${username}")`,
  },

  common: {
    navbar: '.oxd-topbar',
    sidebar: '.oxd-sidebar-body',
    modal: '.oxd-dialog-container',
    confirmButton: 'button:has-text("Confirm")',
    cancelButton: 'button:has-text("Cancel")',
    loadingSpinner: '.oxd-loading-spinner',
    successMessage: '.oxd-toast--success',
    errorAlert: '.oxd-alert--error',
  },
} as const;

export type Selectors = typeof selectors;
